# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 285a482387374d1a3ac801647d3ba7af6802d0276d271cf43c1d301b21d16487c7bc6bec30dd89cce2a32c794fce061c886740ad3d41cce3681b4097c4edaf8b

test:
  secret_key_base: 8b7a7ac1b835c814603679e4318b62f519a1802ba328918fbc58335e63f80bc6d298564417ef177569872704859829e0460f1062c5dcabef891ac8ff7d41b108

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
